name: CI/CD Pipeline for bookapi

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: mitch3192/bookapi:latest

    steps:
      - name: âœ¨ Checkout Code
        uses: actions/checkout@v3

      - name: â˜• Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: â› Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: âœ… Run Django tests
        run: |
          cd bookapi
          python manage.py test

      - name: âš™ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ðŸ“ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: ðŸ›° Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: âœ¨ Deploy to Kubernetes
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG_FILE" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          helm upgrade --install bookapi ./bookapi-chart --namespace default
